# Converting AND to OR gate

In [5]:
import pandas as pd

# TODO: Set weight1, weight2, and bias
weight1 = 0.5
weight2 = 0.2
bias = -0.5130


# DON'T CHANGE ANYTHING BELOW
# Inputs and outputs
test_inputs = [(0, 0), (0, 1), (1, 0), (1, 1)]
correct_outputs = [False, False, False, True]
outputs = []

# Generate and check output
for test_input, correct_output in zip(test_inputs, correct_outputs):
    linear_combination = weight1 * test_input[0] + weight2 * test_input[1] + bias
    output = int(linear_combination >= 0)
    is_correct_string = 'Yes' if output == correct_output else 'No'
    outputs.append([test_input[0], test_input[1], linear_combination, output, is_correct_string])

# Print output
num_wrong = len([output[4] for output in outputs if output[4] == 'No'])
output_frame = pd.DataFrame(outputs, columns=['Input 1', '  Input 2', '  Linear Combination', '  Activation Output', '  Is Correct'])
if not num_wrong:
    print('Nice!  You got it all correct.\n')
else:
    print('You got {} wrong.  Keep trying!\n'.format(num_wrong))
print(output_frame.to_string(index=False))

Nice!  You got it all correct.

 Input 1    Input 2    Linear Combination    Activation Output   Is Correct
       0          0                -0.513                    0          Yes
       0          1                -0.313                    0          Yes
       1          0                -0.013                    0          Yes
       1          1                 0.187                    1          Yes


## NOT gate

In [6]:
import pandas as pd

# TODO: Set weight1, weight2, and bias
weight1 = -0.50
weight2 = -1.512
bias = 0.5

# DON'T CHANGE ANYTHING BELOW
# Inputs and outputs
test_inputs = [(0, 0), (0, 1), (1, 0), (1, 1)]
correct_outputs = [True, False, True, False]
outputs = []

# Generate and check output
for test_input, correct_output in zip(test_inputs, correct_outputs):
    linear_combination = weight1 * test_input[0] + weight2 * test_input[1] + bias
    output = int(linear_combination >= 0)
    is_correct_string = 'Yes' if output == correct_output else 'No'
    outputs.append([test_input[0], test_input[1], linear_combination, output, is_correct_string])

# Print output
num_wrong = len([output[4] for output in outputs if output[4] == 'No'])
output_frame = pd.DataFrame(outputs, columns=['Input 1', '  Input 2', '  Linear Combination', '  Activation Output', '  Is Correct'])
if not num_wrong:
    print('Nice!  You got it all correct.\n')
else:
    print('You got {} wrong.  Keep trying!\n'.format(num_wrong))
print(output_frame.to_string(index=False))

Nice!  You got it all correct.

 Input 1    Input 2    Linear Combination    Activation Output   Is Correct
       0          0                 0.500                    1          Yes
       0          1                -1.012                    0          Yes
       1          0                 0.000                    1          Yes
       1          1                -1.512                    0          Yes


## Testing Perception algorithm of a data set

In [59]:
import numpy as np
# Setting the random seed, feel free to change it and see different solutions.
np.random.seed(42)

def stepFunction(t):
    if t >= 0:
        return 1
    return 0

def prediction(X, W, b):
    return stepFunction((np.matmul(X,W)+b)[0])

# TODO: Fill in the code below to implement the perceptron trick.
# The function should receive as inputs the data X, the labels y,
# the weights W (as an array), and the bias b,
# update the weights and bias W, b, according to the perceptron algorithm,
# and return W and b.
def perceptronStep(X, y, W, b, learn_rate = 0.01):
    for i in range(len(X)):
        y_hat = prediction(X[i],W,b)
        if y[i]-y_hat == 1:
            W[0] += X[i][0]*learn_rate
            W[1] += X[i][1]*learn_rate
            b += learn_rate
        elif y[i]-y_hat == -1:
            W[0] -= X[i][0]*learn_rate
            W[1] -= X[i][1]*learn_rate
            b -= learn_rate
    return W, b
    
# This function runs the perceptron algorithm repeatedly on the dataset,
# and returns a few of the boundary lines obtained in the iterations,
# for plotting purposes.
# Feel free to play with the learning rate and the num_epochs,
# and see your results plotted below.
def trainPerceptronAlgorithm(X, y, learn_rate = 0.01, num_epochs = 25):
    x_min, x_max = min(X.T[0]), max(X.T[0])
    y_min, y_max = min(X.T[1]), max(X.T[1])
    W = np.array(np.random.rand(2,1))
    b = np.random.rand(1)[0] + x_max
    # These are the solution lines that get plotted below.
    boundary_lines = []
    for i in range(num_epochs):
        # In each epoch, we apply the perceptron step.
        W, b = perceptronStep(X, y, W, b, learn_rate)
        boundary_lines.append((-W[0]/W[1], -b/W[1]))
    return boundary_lines

In [60]:
import pandas as pd

In [45]:
pd.read_csv?

In [61]:
df = pd.read_csv("perceptron.txt", delimiter = ",", names =["x1",'x2','y'])
df.head()

x1        x2  y
0  0.78051 -0.063669  1
1  0.28774  0.291390  1
2  0.40714  0.178780  1
3  0.29230  0.421700  1
4  0.50922  0.352560  1

In [62]:
X  = df[['x1','x2']]
y = df.y

In [66]:
X = np.array(X)
y = np.array(y)

In [67]:
trainPerceptronAlgorithm(X,y)

[(array([1.32111616]), array([3.39038455])),
 (array([-0.02727335]), array([0.58093127])),
 (array([-0.06953723]), array([0.5033617])),
 (array([-0.09336359]), array([0.50938365])),
 (array([-0.11776695]), array([0.51555142])),
 (array([-0.14276851]), array([0.52187039])),
 (array([-0.16839056]), array([0.52834619])),
 (array([-0.19465648]), array([0.53498471])),
 (array([-0.20547521]), array([0.57024877])),
 (array([-0.22495207]), array([0.57724872])),
 (array([-0.24289533]), array([0.58594893])),
 (array([-0.26138775]), array([0.5949154])),
 (array([-0.28045492]), array([0.60416056])),
 (array([-0.30012406]), array([0.6136976])),
 (array([-0.32842636]), array([0.5900821])),
 (array([-0.34182866]), array([0.63222086])),
 (array([-0.37108442]), array([0.6079341])),
 (array([-0.38612915]), array([0.65189711])),
 (array([-0.4164041]), array([0.62689996])),
 (array([-0.44025201]), array([0.63605195])),
 (array([-0.44738156]), array([0.67836799])),
 (array([-0.46823366]), array([0.64805537

## Quiz: Coding Softmax
And now, your time to shine! Let's code the formula for the Softmax function in Python.

In [68]:
import numpy as np

# Write a function that takes as input a list of numbers, and returns
# the list of values given by the softmax function.
def softmax(L):
    q=[]
    for i in L:
        z = np.exp(i)/np.exp(sum(L))
        q.append(z)
    return q    

## Solution

In [69]:
import numpy as np

def softmax(L):
    expL = np.exp(L)
    sumExpL = sum(expL)
    result = []
    for i in expL:
        result.append(i*1.0/sumExpL)
    return result
    
    # Note: The function np.divide can also be used here, as follows:
    # def softmax(L):
    #     expL = np.exp(L)
    #     return np.divide (expL, expL.sum())

## Quiz: Coding Cross-entropy
Now, time to shine! Let's code the formula for cross-entropy in Python.

### My solution

In [70]:
import numpy as np

# Write a function that takes as input two lists Y, P,
# and returns the float corresponding to their cross-entropy.
def cross_entropy(Y, P):
    CE = -np.sum(Y * np.log(P) + (1-Y)*np.log(1-P))
    return CE

###  Solution

In [72]:
#np.float_ converts all values to floats irrespective of the type, the aim is to have a continuous variable

import numpy as np

def cross_entropy(Y, P):
    Y = np.float_(Y)
    P = np.float_(P)
    return -np.sum(Y * np.log(P) + (1 - Y) * np.log(1 - P))